### ISSUE TITLE
`IN ?` is a syntax error and `setObject` doesn't accept tuples

### ISSUE THREAD

**Issue by shenanigansd** [darbiadev/darbiadev-onsite#25]
# Summary

There are two distinct problems
- Using a `?` after an `IN` causes a syntax error.
- The parameters can't accept tuples, because `jaydebeapi` passes the parameters directly to `setObject(int,java.lang.Object)`, which only allows implementors of `SQLData`.

# Story

I want to parameterize this query -
```sql
SELECT Orders.ID_Order
FROM Orders
         JOIN OrderDes ON Orders.ID_Order = OrderDes.id_Order
WHERE OrderDes.id_Design IN (103456, 103457)
  AND Orders.cn_Display_Status_06 IN (0, 0.5);
```

## Works in PyCharm

Initial testing in PyCharm using the JDBC driver to connect show that the query is syntactically valid and works.

<details>
  <summary>Screenshots of PyCharm driver and connection</summary>

  ![driver](https://user-images.githubusercontent.com/54628770/214462890-422f171f-16ed-45ea-81ba-d1a3c2643f7d.png)
  ![datasource](https://user-images.githubusercontent.com/54628770/214462887-92ea7a74-e93d-495d-9930-b2036fd56e9b.png)
  ![query](https://user-images.githubusercontent.com/54628770/214462891-01184747-8f9f-4666-8b06-a690a08b88bd.png)
</details>

## Works in the client

Copied and pasted the query into the client, and it still works.

## Parameterization error

With the query working, I changed the query to accept parameters - 
```diff
- WHERE OrderDes.id_Design IN (103456, 103457)
+ WHERE OrderDes.id_Design IN ?
```

Which... threw a syntax error.
```
Traceback (most recent call last):
  File "com.filemaker.jdbc2.CommonJ2Connection.java", line -1, in com.filemaker.jdbc2.CommonJ2Connection.prepareStatement
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\BradleyReynolds\AppData\Roaming\JetBrains\PyCharm2022.3\scratches\scratch.py", line 25, in <module>
    print(_make_query(query=query_, parameters=parameters_))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BradleyReynolds\AppData\Roaming\JetBrains\PyCharm2022.3\scratches\scratch.py", line 16, in _make_query
    return client.make_query(query, parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BradleyReynolds\dev\idi\scripts\venv\Lib\site-packages\darbiadev_onsite\__init__.py", line 41, in make_query
    cursor.execute(sql, parameters)
  File "C:\Users\BradleyReynolds\dev\idi\scripts\venv\Lib\site-packages\jaydebeapi\__init__.py", line 531, in execute
    self._prep = self._connection.jconn.prepareStatement(operation)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
com.filemaker.jdbc.com.filemaker.jdbc.FMSQLException: com.filemaker.jdbc.FMSQLException: [FileMaker][FileMaker JDBC] FQL0001/(4:8): There is an error in the syntax of the query.

Process finished with exit code 1
```

# Parameter type error

Oh. Okay... Just to check, is it valid with an `=` instead of an `IN`?
```diff
- WHERE OrderDes.id_Design IN ?
+ WHERE OrderDes.id_Design = ?
```
```
Traceback (most recent call last):
  File "C:\Users\BradleyReynolds\AppData\Roaming\JetBrains\PyCharm2022.3\scratches\scratch.py", line 26, in <module>
    print(_make_query(query=query_, parameters=parameters_))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BradleyReynolds\AppData\Roaming\JetBrains\PyCharm2022.3\scratches\scratch.py", line 16, in _make_query
    return client.make_query(query, parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BradleyReynolds\dev\idi\scripts\venv\Lib\site-packages\darbiadev_onsite\__init__.py", line 41, in make_query
    cursor.execute(sql, parameters)
  File "C:\Users\BradleyReynolds\dev\idi\scripts\venv\Lib\site-packages\jaydebeapi\__init__.py", line 532, in execute
    self._set_stmt_parms(self._prep, parameters)
  File "C:\Users\BradleyReynolds\dev\idi\scripts\venv\Lib\site-packages\jaydebeapi\__init__.py", line 523, in _set_stmt_parms
    prep_stmt.setObject(i + 1, parameters[i])
TypeError: No matching overloads found for java.sql.PreparedStatement.setObject(int,tuple), options are:
	public abstract void java.sql.PreparedStatement.setObject(int,java.lang.Object,int) throws java.sql.SQLException
	public default void java.sql.PreparedStatement.setObject(int,java.lang.Object,java.sql.SQLType,int) throws java.sql.SQLException
	public abstract void java.sql.PreparedStatement.setObject(int,java.lang.Object,int,int) throws java.sql.SQLException
	public default void java.sql.PreparedStatement.setObject(int,java.lang.Object,java.sql.SQLType) throws java.sql.SQLException
	public abstract void java.sql.PreparedStatement.setObject(int,java.lang.Object) throws java.sql.SQLException
```
Crap.

# Hypothesis

With the first [syntax] error, I don't understand why introducing parameters causes a syntax error.
Shouldn't the parameters be parsed before the syntax is generated?
I'm worried that the problem will be in FileMaker's JDBC driver, which is closed source, and I'll be stuck unable to fix this; but... the non-parameterized query does work through the driver in both PyCharm and this client. So I'm hoping I'll be able to fix my error by patching `jaydebeapi`, which is open source, or by performing type conversion/coercion within the existing libraries.

The second [type] error seems to be much simpler. Looks like I'd have to monkey patch `jaydebeapi` to coerce the tuples to be valid types for `setObject`.

# Possible solutions

Unclear until I understand the cause.

It's worth creating a Java MVP to test if the same issue occurs without Python messing everything up, though this should be considered a worst case scenario, because all of the Python consumers would have to be rewritten against a new API

# Notes and links

- The [FileMaker JDBC help page](https://help.claris.com/en/pro-help/content/odbc-jdbc.html) links to the [JDBC guide](https://help.claris.com/en/odbc-jdbc-guide.pdf) and the [SQL reference](https://help.claris.com/en/sql-reference.pdf).
- `PreparedStatement`
  - src: https://github.com/openjdk/jdk/blob/master/src/java.sql/share/classes/java/sql/PreparedStatement.java
  - docs: https://docs.oracle.com/en/java/javase/19/docs/api/java.sql/java/sql/PreparedStatement.html
- `jaydebeapi` calls directly to `setObject(int,java.lang.Object)`
  - https://github.com/baztian/jaydebeapi/blob/master/jaydebeapi/__init__.py#L520-L523
  - https://docs.oracle.com/en/java/javase/19/docs/api/java.sql/java/sql/PreparedStatement.html#setObject(int,java.lang.Object)
- [JPype](https://github.com/jpype-project/jpype) is what makes accessing Java possible

**Comment by shenanigansd** [comment]
I asked for help and was told to try generating the parameters for the SQL. I _swear_ I tried `(?)` earlier and it didn't work, but it's working now, so... must have been the demo gods...

I was given this snippet, which actually looks like exactly what I need. With this, I shouldn't actually need to change this package at all.
```py
# https://discord.com/channels/267624335836053506/463035241142026251/1067644929087651920
placeholders = ",".join(["?" for _ in len(args)]
sql = f"SELECT * FROM tablename WHERE columnname IN ({placeholders})"
cursor.execute(sql, args)
```
